apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuck45
  labels:
    app: fuck45
spec:
  selector:
    matchLabels:
      app: fuck45
  template:
    metadata:
      labels:
        app: fuck45
    spec:
      containers:
        - name: fuck45
          image: fuck45:latest
          ports:
            - containerPort: 8000
